spring:
  application:
    name: cafe-crm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVER}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true

paths:
  api:
    version: 1
    prefix: /api/v${paths.api.version}
